services:
  - type: web
    name: coinpulse-bot
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 8696394019:AAEN_9-u1gIly8O39WmTMJ9wuV_uBO7VfKg
      - key: TELEGRAM_CHAT_ID
        value: -5544970151
      - key: THRESHOLDS
        value: 10,15,20
      - key: MIN_VOLUME
        value: 5000000
